services:
  - type: web
    name: chatapp
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
